spring:
  application:
    name: blog-application
  datasource:
    username: admin
    password: Password@123
    url: jdbc:mysql://localhost:3306/blog_db
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
logging:
  level:
    org:
      springframework:
        security: DEBUG