spring:
  application:
    name: blog-application
  datasource:
    username: admin
    password: Password@123
    url: jdbc:mysql://localhost:3306/blog_db
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-circular-references: true
logging:
  level:
    org:
      springframework:
        security: DEBUG
server:
  forward-headers-strategy: framework
app:
  jwt-expiration-milliseconds: '3600000'
  jwt-secret: JWTSecretKey